stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t registry.abzt.de/frontend-app-learning-lilac:0.3.1 .

push:
  stage: push
  script:
    - docker login registry.abzt.de -u gitlab -p $DOCKER_REGISTRY_PASSWORD
    - docker push registry.abzt.de/frontend-app-learning-lilac:0.3.1
